### ISSUE TITLE
Setup MiMa for ensuring binary compatibility

### ISSUE THREAD

**Issue by satabin** [gnieh/fs2-data#122]
Maybe have a look at https://github.com/scalacenter/sbt-version-policy

**Comment by armanbilge** [comment]
Noticed this issue. You may find sbt-typelevel helpful, highly recommended 😉 
https://typelevel.org/sbt-typelevel/

**Comment by armanbilge** [comment]
For sbt-typelevel to be stable? Whether I like it or not it has to be stable now, because there are too many builds using it and I don't want to redo them 😆
- https://github.com/typelevel/sbt-typelevel/issues/83

**Comment by satabin** [comment]
Ok sorry last time I checked it was still in early stages, I will try the migration.

**Comment by satabin** [comment]
Closed by #315
