### ISSUE TITLE
XML roundtrip failing on &amp;

### ISSUE THREAD

**Issue by ybasket** [gnieh/fs2-data#503]
The roundtrip tests in http4s-fs2-data are flaky, they sometimes fail on escaped entities:
https://github.com/http4s/http4s-fs2-data/actions/runs/5514890884/job/14930647806?pr=97 (only `&amp;`)
and https://github.com/http4s/http4s-fs2-data/actions/runs/5481925805/job/14845710701 (combined with a `lt`).

It's not yet clear whether the input is actually invalid XML or fs2-data handles it incorrectly, to be investigated.

**Comment by satabin** [comment]
Failing data from above are:
```xml
<戝蜷븝낌畏:彵ᾋ銋궜来鯒妓鐡뗑 痴놰绯猿Đ꺠询:尵蜙헕稜籟="硗잤왠" 팩菾聢魣ந넞="瀝&amp;䇉"/>
```

and

```xml
<碅旜귣锍橨礶:齸踡軽걪폄駗 븁彦="纭徍膽挚訥௿尦" 期煫俠뀊뿕慉="剧ﱄ蘊儒ﴓ黢" 뇄揆瓊议鋐宇="岒᚛抂밐侷">ￇ뽚昄옌&amp;lt;熞㸑䁛ን탂Ꚁ혆⥕ᰓ䖐铭콾Ḡᙵ</碅旜귣锍橨礶:齸踡軽걪폄駗>
```

**Comment by ybasket** [comment]
Yes, it seems caused by Scala-xml's faulty behavior. I was able to work around the problem in http4s-fs2-data by adjusting its test generators, hence closing this issue.
