### ISSUE TITLE
Feature request: cell encoder from `cats.Show`?

### ISSUE THREAD

**Issue by vreuter** [gnieh/fs2-data#609]
Hi, many thanks for an excellent library! I wonder if in the CSV part of this project there'd be interest in adding a small convenience helper -- the capability to build a `CellEncoder` instance for a type based on the presence of a `cats.Show` instance for the same type. Maybe just to the `CellEncoder` companion object, to complement `fromToString[A]`? So something like:
```scala
object CellEncoder:
    ...
    def fromShow[T : Show]: CellEncoder[T] = instance(summon[Show[T]].show)
    ...
```
Any chance to add this as a helper for building encoders?

**Comment by ybasket** [comment]
Sounds like a reasonable addition! Want to give it a try and open a PR?

**Comment by vreuter** [comment]
Yes, I'll give it a shot :)
