### ISSUE TITLE
Derivations when `case class` in question has context bound(s)

### ISSUE THREAD

**Issue by vreuter** [gnieh/fs2-data#610]
I have a case class for which I'd like to derive a `CsvRowDecoder`, and I ran into an issue seeming to arise because of the requirement for a typeclass instance for some of my case class's members. More specifically, I have fields in my case class which are value class-like, being case classes themselves and wrapping just a single (public) value. Because of what these fields represent, I bound the type parameter for the case class for each as `Numeric`.

Here's a relatively minimal example, working with using version 1.11.0 of `fs2-data`, with Scala 3.4.2.
```scala
scala> import fs2.data.*
     | import fs2.data.csv.*
     | import fs2.data.csv.generic.*
     | import fs2.data.csv.generic.semiauto.*
     |
     | final case class MyC1[C : Numeric](get: C)
     |
     | type Wrapped = Double
     | type C1 = MyC1[Wrapped]
     |
// defined case class MyC1
// defined alias type Wrapped = Double
// defined alias type C1 = MyC1[Wrapped]

scala> val dec1: CsvRowEncoder[C1, String] = deriveCsvRowEncoder[C1]
     |
-- [E172] Type Error: ----------------------------------------------------------
1 |val dec1: CsvRowEncoder[C1, String] = deriveCsvRowEncoder[C1]
  |                                                             ^
  |No given instance of type shapeless3.deriving.K0.ProductInstances[fs2.data.csv.CellEncoder, C1] was found for parameter ic of method deriveCsvRowEncoder in object semiauto.
  |I found:
  |
  |    shapeless3.deriving.K0.mkProductInstances[fs2.data.csv.CellEncoder,
  |      MyC1[Wrapped]](
  |      /* missing */summon[shapeless3.deriving.K0.ProductGeneric[MyC1[Wrapped]]])
  |
  |But Failed to synthesize an instance of type shapeless3.deriving.K0.ProductGeneric[MyC1[Wrapped]]: class MyC1 is not a generic product because it takes more than one parameter list.
1 error found
```

I can work around this by making the wrapped member private and then requiring the `Numeric` instance only when it's accessed by a named alias, but it feels hacky and overly complex. 
```scala
scala> final case class MyC2[C](private val value: C):
     |     def get(using Numeric[C]): C = value
     |
     | type C2 = MyC2[Wrapped]
     |
     | val dec2: CsvRowEncoder[C2, String] = deriveCsvRowEncoder[C2]
     |
// defined case class MyC2
// defined alias type C2 = MyC2[Wrapped]
val dec2: fs2.data.csv.CsvRowEncoder[C2, String] = fs2.data.csv.generic.semiauto$$anon$12@42d2685
```

Am I missing a simpler and/or more sound way in which this sort of thing is possible?

**Comment by satabin** [comment]
Thanks for reporting. This looks like a limitation on shapeless3. I am not really familiar with it, I must admit. I will investigate if there is a way to get around this.

**Comment by satabin** [comment]
I experimented a bit with it, and as I suspected this is a limitation, but not in shapeless, in Scala 3. You do not get a `Mirror.ProductOf` for a case class with context bound (or any other case class with more than one parameter list, which a context bound desugars to).

For instance, if you take the derivation example from the documentation and try to derive an `Eq` for such a class, you get the same error: https://scastie.scala-lang.org/V48BYfEVQcaJiMOPcFboEQ

There is not much we can do about it, it is a language limitation. I could argue that a case class should not have context bound on their constructor as they should represent pure data, and that `Numeric` (or any context bound) is more on the behavior side, so your workaround would be one way to deal with it while respecting this approach.

**Comment by vreuter** [comment]
Thanks a lot for looking at this @satabin . Indeed, it felt a bit overly restrictive / inflexible / generally fishy putting the requirement for the `Numeric` right in the constructor. I'll stick w/ the current workaround approach then, feeling a bit better about it than I did at first :)

Thank again!
